/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings ./src/worker-configuration.d.ts` (hash: 1508a38007670f70431bc7999912db2d)
interface __BaseEnv_CloudflareBindings {
	ASSETS: R2Bucket;
	DB: D1Database;
	BETTER_AUTH_URL: "https://api.un-fra.me";
	DEVICE_CLIENT_ID: "unframe-unity";
	WEB_ORIGIN: "https://un-fra.me";
	R2_ACCOUNT_ID: "replace-with-r2-account-id";
	R2_BUCKET_NAME: "unframe-assets";
	REALTIME_ENDPOINT: "https://realtime.un-fra.me";
	REALTIME_ISSUER: "https://api.un-fra.me";
	REALTIME_SIGNING_KID: "realtime-2026-08";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_URL" | "DEVICE_CLIENT_ID" | "WEB_ORIGIN" | "R2_ACCOUNT_ID" | "R2_BUCKET_NAME" | "REALTIME_ENDPOINT" | "REALTIME_ISSUER" | "REALTIME_SIGNING_KID">> {}
}
