/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings ./src/worker-configuration.d.ts` (hash: 8fc13c377e4a3fcc35aedeb768d57400)
interface __BaseEnv_CloudflareBindings {
	ASSETS: R2Bucket;
	DB: D1Database;
	BETTER_AUTH_URL: "https://api.un-fra.me";
	DEVICE_CLIENT_ID: "unframe-unity";
	WEB_ORIGIN: "https://un-fra.me";
	R2_ACCOUNT_ID: "5e51990fc7286bc6106950b1617361c9";
	R2_BUCKET_NAME: "unframe-assets";
	REALTIME_ENDPOINT: "https://realtime.un-fra.me";
	REALTIME_ISSUER: "https://api.un-fra.me";
	REALTIME_SIGNING_KID: "realtime-2026-08";
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_API_KEY: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	RESEND_API_KEY: string;
	AUTH_EMAIL_FROM: string;
	R2_ACCESS_KEY_ID: string;
	R2_SECRET_ACCESS_KEY: string;
	REALTIME_SIGNING_JWK: string;
	SERVICE_IDENTITY_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_URL" | "DEVICE_CLIENT_ID" | "WEB_ORIGIN" | "R2_ACCOUNT_ID" | "R2_BUCKET_NAME" | "REALTIME_ENDPOINT" | "REALTIME_ISSUER" | "REALTIME_SIGNING_KID" | "BETTER_AUTH_SECRET" | "BETTER_AUTH_API_KEY" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "RESEND_API_KEY" | "AUTH_EMAIL_FROM" | "R2_ACCESS_KEY_ID" | "R2_SECRET_ACCESS_KEY" | "REALTIME_SIGNING_JWK" | "SERVICE_IDENTITY_SECRET">> {}
}
