/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings ./src/worker-configuration.d.ts` (hash: 2a376219614cc0220a70b4da13438fbd)
interface __BaseEnv_CloudflareBindings {
	ASSETS: R2Bucket;
	DB: D1Database;
	BETTER_AUTH_URL: "https://api.un-fra.me";
	DEVICE_CLIENT_ID: "unframe-unity";
	WEB_ORIGIN: "https://un-fra.me";
	R2_ACCOUNT_ID: "replace-with-r2-account-id";
	R2_BUCKET_NAME: "unframe-assets";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_URL" | "DEVICE_CLIENT_ID" | "WEB_ORIGIN" | "R2_ACCOUNT_ID" | "R2_BUCKET_NAME">> {}
}
