// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package sqlcgen

import (
	"context"
	"strings"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (id, filename, mime_type, size_bytes, storage_key)
VALUES (?, ?, ?, ?, ?)
RETURNING id, filename, mime_type, size_bytes, storage_key, created_at
`

type CreateAssetParams struct {
	ID         string `json:"id"`
	Filename   string `json:"filename"`
	MimeType   string `json:"mime_type"`
	SizeBytes  int64  `json:"size_bytes"`
	StorageKey string `json:"storage_key"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, createAsset,
		arg.ID,
		arg.Filename,
		arg.MimeType,
		arg.SizeBytes,
		arg.StorageKey,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.MimeType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT id, filename, mime_type, size_bytes, storage_key, created_at
FROM assets
WHERE id = ?
`

func (q *Queries) GetAsset(ctx context.Context, id string) (Asset, error) {
	row := q.db.QueryRowContext(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.MimeType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CreatedAt,
	)
	return i, err
}

const listAssetsByIDs = `-- name: ListAssetsByIDs :many
SELECT id, filename, mime_type, size_bytes, storage_key, created_at
FROM assets
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) ListAssetsByIDs(ctx context.Context, ids []string) ([]Asset, error) {
	query := listAssetsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.MimeType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
