// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error)
	CreatePresentation(ctx context.Context, arg CreatePresentationParams) error
	CreateSlide(ctx context.Context, arg CreateSlideParams) error
	DeletePresentationSlides(ctx context.Context, presentationID string) error
	GetAsset(ctx context.Context, id string) (Asset, error)
	GetPresentation(ctx context.Context, id string) (GetPresentationRow, error)
	GetSingletonPresentationID(ctx context.Context) (string, error)
	ListAssetsByIDs(ctx context.Context, ids []string) ([]Asset, error)
	ListPresentationSlides(ctx context.Context, presentationID string) ([]ListPresentationSlidesRow, error)
	ListPresentations(ctx context.Context) ([]ListPresentationsRow, error)
	UpdatePresentation(ctx context.Context, arg UpdatePresentationParams) error
}

var _ Querier = (*Queries)(nil)
