// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
)

type Asset struct {
	ID         string `json:"id"`
	Filename   string `json:"filename"`
	MimeType   string `json:"mime_type"`
	SizeBytes  int64  `json:"size_bytes"`
	StorageKey string `json:"storage_key"`
	CreatedAt  string `json:"created_at"`
}

type Presentation struct {
	ID               string         `json:"id"`
	SingletonKey     int64          `json:"singleton_key"`
	Title            string         `json:"title"`
	ThumbnailAssetID sql.NullString `json:"thumbnail_asset_id"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type Slide struct {
	ID             string `json:"id"`
	PresentationID string `json:"presentation_id"`
	OrderIndex     int64  `json:"order_index"`
	Content        string `json:"content"`
	CreatedAt      string `json:"created_at"`
	UpdatedAt      string `json:"updated_at"`
}
