// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: presentations.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createPresentation = `-- name: CreatePresentation :exec
INSERT INTO presentations (id, title, thumbnail_asset_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?)
`

type CreatePresentationParams struct {
	ID               string         `json:"id"`
	Title            string         `json:"title"`
	ThumbnailAssetID sql.NullString `json:"thumbnail_asset_id"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

func (q *Queries) CreatePresentation(ctx context.Context, arg CreatePresentationParams) error {
	_, err := q.db.ExecContext(ctx, createPresentation,
		arg.ID,
		arg.Title,
		arg.ThumbnailAssetID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createSlide = `-- name: CreateSlide :exec
INSERT INTO slides (id, presentation_id, order_index, content)
VALUES (?, ?, ?, ?)
`

type CreateSlideParams struct {
	ID             string `json:"id"`
	PresentationID string `json:"presentation_id"`
	OrderIndex     int64  `json:"order_index"`
	Content        string `json:"content"`
}

func (q *Queries) CreateSlide(ctx context.Context, arg CreateSlideParams) error {
	_, err := q.db.ExecContext(ctx, createSlide,
		arg.ID,
		arg.PresentationID,
		arg.OrderIndex,
		arg.Content,
	)
	return err
}

const deletePresentationSlides = `-- name: DeletePresentationSlides :exec
DELETE FROM slides
WHERE presentation_id = ?
`

func (q *Queries) DeletePresentationSlides(ctx context.Context, presentationID string) error {
	_, err := q.db.ExecContext(ctx, deletePresentationSlides, presentationID)
	return err
}

const getPresentation = `-- name: GetPresentation :one
SELECT id, title, thumbnail_asset_id, created_at, updated_at
FROM presentations
WHERE id = ?
`

type GetPresentationRow struct {
	ID               string         `json:"id"`
	Title            string         `json:"title"`
	ThumbnailAssetID sql.NullString `json:"thumbnail_asset_id"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

func (q *Queries) GetPresentation(ctx context.Context, id string) (GetPresentationRow, error) {
	row := q.db.QueryRowContext(ctx, getPresentation, id)
	var i GetPresentationRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ThumbnailAssetID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSingletonPresentationID = `-- name: GetSingletonPresentationID :one
SELECT id
FROM presentations
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetSingletonPresentationID(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getSingletonPresentationID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listPresentationSlides = `-- name: ListPresentationSlides :many
SELECT id, order_index, content, updated_at
FROM slides
WHERE presentation_id = ?
ORDER BY order_index ASC
`

type ListPresentationSlidesRow struct {
	ID         string `json:"id"`
	OrderIndex int64  `json:"order_index"`
	Content    string `json:"content"`
	UpdatedAt  string `json:"updated_at"`
}

func (q *Queries) ListPresentationSlides(ctx context.Context, presentationID string) ([]ListPresentationSlidesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPresentationSlides, presentationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPresentationSlidesRow
	for rows.Next() {
		var i ListPresentationSlidesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderIndex,
			&i.Content,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPresentations = `-- name: ListPresentations :many
SELECT id, title, thumbnail_asset_id, created_at, updated_at
FROM presentations
ORDER BY created_at DESC
`

type ListPresentationsRow struct {
	ID               string         `json:"id"`
	Title            string         `json:"title"`
	ThumbnailAssetID sql.NullString `json:"thumbnail_asset_id"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

func (q *Queries) ListPresentations(ctx context.Context) ([]ListPresentationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPresentations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPresentationsRow
	for rows.Next() {
		var i ListPresentationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ThumbnailAssetID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePresentation = `-- name: UpdatePresentation :exec
UPDATE presentations
SET
    title = CASE WHEN ?1 THEN ?2 ELSE title END,
    thumbnail_asset_id = CASE
        WHEN ?3 THEN ?4
        ELSE thumbnail_asset_id
    END,
    updated_at = ?5
WHERE id = ?6
`

type UpdatePresentationParams struct {
	SetTitle            string         `json:"set_title"`
	Title               string         `json:"title"`
	SetThumbnailAssetID sql.NullString `json:"set_thumbnail_asset_id"`
	ThumbnailAssetID    sql.NullString `json:"thumbnail_asset_id"`
	UpdatedAt           string         `json:"updated_at"`
	ID                  string         `json:"id"`
}

func (q *Queries) UpdatePresentation(ctx context.Context, arg UpdatePresentationParams) error {
	_, err := q.db.ExecContext(ctx, updatePresentation,
		arg.SetTitle,
		arg.Title,
		arg.SetThumbnailAssetID,
		arg.ThumbnailAssetID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
