import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { assert, expect, it } from "vitest";
import { openOpaqueCaptureRuntime } from "../src/opaque/capture/runtime.js";

const liberation = readFileSync(
  fileURLToPath(
    new URL("../../../app/unity/Assets/TextMesh Pro/Fonts/LiberationSans.ttf", import.meta.url),
  ),
).toString("base64");
const font = { dataBase64: liberation, mediaType: "font/ttf", path: "fonts/liberation.ttf" };
const noto = {
  dataBase64: readFileSync(
    fileURLToPath(new URL("./fixtures/UnframeFixtureCJK-Regular.otf", import.meta.url)),
  ).toString("base64"),
  mediaType: "font/otf",
  path: "fonts/cjk.otf",
};
const stylesheet = (css: string) => ({
  dataBase64: Buffer.from(css).toString("base64"),
  mediaType: "text/css",
  path: "fonts.css",
});
const face = `@font-face{font-family:Fixture;src:url('/fonts/liberation.ttf');font-style:normal;font-weight:400}`;
const cjkFace = `@font-face{font-family:CJK;src:url('/fonts/cjk.otf');font-style:normal;font-weight:400 700}`;
const request = (text: string, css: string, assets = [font]) => ({
  assets: [...assets, stylesheet(css)],
  background: [0, 0, 0, 0] as const,
  colorScheme: "light" as const,
  expectedBindings: { "node:title": text },
  javascript: `globalThis.__unframeMount=()=>{const text=document.createElement('span');text.dataset.unframeBinding='node:title';text.textContent=${JSON.stringify(text)};document.getElementById('unframe-root').append(text);};`,
  logicalSize: [160, 90] as const,
  pixelTarget: [160, 90] as const,
  props: {},
  stateId: "default",
  stylesheets: ["fonts.css"],
  texts: { title: text },
});

it("captures text using an explicit locked font and preserves transparent pixels", async () => {
  const runtime = await openOpaqueCaptureRuntime();
  try {
    const result = await runtime.capture(request("Hello", `${face} span{font-family:Fixture}`));
    assert.isTrue(result.ok);
    expect([...Buffer.from(result.rgbaBase64, "base64").subarray(-4)]).toEqual([0, 0, 0, 0]);
  } finally {
    await runtime.close();
  }
}, 60_000);

it("rejects a visible OS fallback font", async () => {
  const runtime = await openOpaqueCaptureRuntime();
  try {
    expect(await runtime.capture(request("Hello", "span{font-family:serif}", []))).toMatchObject({
      code: "opaque-font-unlocked",
      ok: false,
    });
  } finally {
    await runtime.close();
  }
}, 60_000);

it("rejects bold text without a locked 700 face", async () => {
  const runtime = await openOpaqueCaptureRuntime();
  try {
    expect(
      await runtime.capture(request("Bold", `${face} span{font-family:Fixture;font-weight:700}`)),
    ).toMatchObject({ code: "opaque-font-unlocked", ok: false });
  } finally {
    await runtime.close();
  }
}, 60_000);

it("rejects a 700 declaration backed by a regular-only font file", async () => {
  const runtime = await openOpaqueCaptureRuntime();
  try {
    expect(
      await runtime.capture(
        request(
          "Bold",
          `${face.replace("font-weight:400", "font-weight:400 700")} span{font-family:Fixture;font-weight:700}`,
        ),
      ),
    ).toMatchObject({ code: "opaque-font-invalid", ok: false });
  } finally {
    await runtime.close();
  }
}, 60_000);

it("rejects a missing Japanese glyph instead of accepting a fallback glyph", async () => {
  const runtime = await openOpaqueCaptureRuntime();
  try {
    expect(
      await runtime.capture(request("日本語", `${face} span{font-family:Fixture}`)),
    ).toMatchObject({
      code: "opaque-font-glyph-missing",
      ok: false,
    });
  } finally {
    await runtime.close();
  }
}, 60_000);

it("captures Japanese and Latin text with two locked fallback faces", async () => {
  const runtime = await openOpaqueCaptureRuntime();
  try {
    const result = await runtime.capture(
      request("Hello 日本語", `${face}${cjkFace} span{font-family:Fixture,CJK}`, [font, noto]),
    );
    assert.isTrue(result.ok, JSON.stringify(result));
    expect(result.bindings[0]?.text).toBe("Hello 日本語");
  } finally {
    await runtime.close();
  }
}, 60_000);

it("captures bold text with a locked variable-weight face", async () => {
  const runtime = await openOpaqueCaptureRuntime();
  try {
    const result = await runtime.capture(
      request("Bold 日本語", `${cjkFace} span{font-family:CJK;font-weight:700}`, [noto]),
    );
    assert.isTrue(result.ok, JSON.stringify(result));
  } finally {
    await runtime.close();
  }
}, 60_000);

it("rejects text generated by a pseudo element until its glyphs can be inspected", async () => {
  const runtime = await openOpaqueCaptureRuntime();
  try {
    const input = request("", `${face} span{font-family:Fixture} span::before{content:'Hello'}`);
    expect(await runtime.capture(input)).toMatchObject({ code: "opaque-font-invalid", ok: false });
  } finally {
    await runtime.close();
  }
}, 60_000);
